In [4]:
import pandas as pd
pd.options.display.max_rows = 999

In [20]:
df = pd.read_excel('../data/raw/2023/Режимный_лист_МУИС_2023.xlsx', sheet_name='Март 2023')

In [25]:
df.iloc[90:110,[0, 56, 31]]

,Режимный лист МУИС-2500 Воронцовского месторождения,Unnamed: 56,Unnamed: 31
90,20:00:00,NaN,61.805
91,22:00:00,NaN,30.733
92,00:00:00,NaN,78.158
93,NaN,NaN,NaN
94,Дата/Время мск,Добыча воды за 2 ч,NaN
95,NaN,NaN,Показания влагомера
96,NaN,м3,NaN
97,NaN,2.459747,% обводненности
98,2023-03-01 00:00:00,2.425342,0.1
99,02:00:00,2.365038,0.11
100,04:00:00,2.421466,0.11
101,06:00:00,2.528735,0.13
102,08:00:00,2.936393,0.11
103,10:00:00,1.985546,0.12
104,12:00:00,2.29821,0.13
105,14:00:00,2.474794,0.1
106,16:00:00,2.200502,0.11
107,18:00:00,2.452765,0.11
108,20:00:00,2.511842,0.09
109,22:00:00,2.372661,0.1